// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "github.com/gojek/optimus-extension-valor/model"
	mock "github.com/stretchr/testify/mock"
)

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// Next provides a mock function with given fields:
func (_m *Reader) Next() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Read provides a mock function with given fields:
func (_m *Reader) Read() (*model.Data, error) {
	ret := _m.Called()

	var r0 *model.Data
	if rf, ok := ret.Get(0).(func() *model.Data); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Data)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
