// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "github.com/gojek/optimus-extension-valor/model"
	mock "github.com/stretchr/testify/mock"
)

// Writer is an autogenerated mock type for the Writer type
type Writer struct {
	mock.Mock
}

// Write provides a mock function with given fields: _a0
func (_m *Writer) Write(_a0 *model.Data) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Data) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
